theme: "hugo-xmin"
baseURL: "https://adshahbaaz.netlify.app/"
languageCode: "en-us"
title: ""
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "â†©"
relativeURLs: true


menu:
 main:
  - name: Home
    url: ""
    weight: 1
  - name: About
    url: "about/"
    weight: 2
  - name: Categories
    url: "categories/"
    weight: 3
  - name: GitHub
    url: https://github.com/adshahbaaz
    weight: 4    

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true